In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
myproduct=pd.read_csv("D:\\Desktop\\python\\Num\\product.csv")
myproduct.head()

ID  Year_of_Birth Education_Level Marital_Status  \
0  ID_4A9AR6FQ           1955      Graduation       Divorced   
1  ID_X28T3VEK           1958      Graduation       Together   
2  ID_AWXARH57           1962      Graduation         Single   
3  ID_FQVZHE81           1979        2n Cycle         Single   
4  ID_QVLWGPRN           1959      Graduation        Married   

   Disposable_Income  No_of_Kids_in_home  No_of_Teen_in_home Date_Customer  \
0            77504.4                   1                   1    22-06-2014   
1            56784.0                   0                   1    01-08-2013   
2           103714.8                   0                   0    21-11-2013   
3            46311.6                   1                   0    13-09-2013   
4            87486.0                   0                   0    21-01-2014   

   Recency  Discounted_Purchases  ...  Amount_on_SweetProducts  \
0       56                     2  ...                        6   
1       17                     6  ...                       15   
2       17                     0  ...                       18   
3       49                     3  ...                       24   
4       59                     1  ...                      165   

   Amount_on_GoldProds  WebVisitsMonth  Cmp3Accepted  Cmp4Accepted  \
0                   20               3             0             0   
1                   19               6             0             0   
2                   37               2             0             0   
3                   24               8             0             0   
4                  203               1             0             0   

   Cmp5Accepted  Cmp1Accepted  Cmp2Accepted  Any_Complain  Response  
0             0             0             0             0         0  
1             0             0             0             0         0  
2             0             1             0             0         1  
3             0             0             0             0         0  
4             0             1             0             0         0  

[5 rows x 27 columns]

In [4]:
year=np.array(myproduct["Year_of_Birth"])
edu=np.array(myproduct["Education_Level"])
sta=np.array(myproduct["Marital_Status"])
kid=np.array(myproduct["No_of_Kids_in_home"])
teen=np.array(myproduct["No_of_Teen_in_home"])

TypeError: _sum_dispatcher() missing 1 required positional argument: 'a'

In [6]:
myproduct.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1568 entries, 0 to 1567
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   ID                       1568 non-null   object 
 1   Year_of_Birth            1568 non-null   int64  
 2   Education_Level          1568 non-null   object 
 3   Marital_Status           1568 non-null   object 
 4   Disposable_Income        1552 non-null   float64
 5   No_of_Kids_in_home       1568 non-null   int64  
 6   No_of_Teen_in_home       1568 non-null   int64  
 7   Date_Customer            1568 non-null   object 
 8   Recency                  1568 non-null   int64  
 9   Discounted_Purchases     1568 non-null   int64  
 10  WebPurchases             1568 non-null   int64  
 11  CatalogPurchases         1568 non-null   int64  
 12  StorePurchases           1568 non-null   int64  
 13  Amount_on_Wines          1568 non-null   int64  
 14  Amount_on_Fruits        

In [7]:
wines=np.array(myproduct["Amount_on_Wines"])
wines

array([ 71, 205, 469, ..., 820,  57,  18], dtype=int64)

In [8]:
np.sum(wines)

475402

In [11]:
fruits=np.array(myproduct["Amount_on_Fruits"])
fruits

array([ 3, 22, 31, ..., 11,  3,  5], dtype=int64)

In [12]:
np.sum(fruits)

45615

In [14]:
meats=np.array(myproduct["Amount_on_MeatProducts"])
meats

array([ 16, 111, 873, ...,  53,   9,  18], dtype=int64)

In [15]:
np.sum(meats)

264014

In [16]:
fish=np.array(myproduct["Amount_on_FishProducts"])
fish

array([ 0, 50, 29, ..., 11,  0,  6], dtype=int64)

In [17]:
np.sum(fish)

58277

In [19]:
newarr=np.array(myproduct)
newarr

array([['ID_4A9AR6FQ', 1955, 'Graduation', ..., 0, 0, 0],
       ['ID_X28T3VEK', 1958, 'Graduation', ..., 0, 0, 0],
       ['ID_AWXARH57', 1962, 'Graduation', ..., 0, 0, 1],
       ...,
       ['ID_O11VSIJY', 1952, 'Master', ..., 0, 0, 0],
       ['ID_VS37P6MS', 1964, 'PhD', ..., 0, 0, 0],
       ['ID_AKHOY7EI', 1970, 'Graduation', ..., 0, 0, 0]], dtype=object)

In [20]:
arr=newarr[:,[2,14,15,16]]
arr

array([['Graduation', 3, 16, 0],
       ['Graduation', 22, 111, 50],
       ['Graduation', 31, 873, 29],
       ...,
       ['Master', 11, 53, 11],
       ['PhD', 3, 9, 0],
       ['Graduation', 5, 18, 6]], dtype=object)

In [21]:
grafruitlist=[]
otherlist=[]
for x in arr:
    if x[0]=="Graduation":
        grafruitlist.append(x[1])
    else:
        otherlist.append(x[1])
        

In [22]:
gra=np.array(grafruitlist)
gra

array([  3,  22,  31, 117,  31,  94,   4,   6,   9,  22,   8,   5,  13,
         3,   3,  48,  56,   3,  20,   4,   3,   3,  15,   6, 132,  12,
        47,  52,   3,   7,  12,   7,   3,   7,  17, 111,   4,   4,   5,
        47,   8,   3,   3,  18,  26,   3,  37,   3,   9,   3,   6,   3,
         3, 147,  14,   7,   7,   9,   3, 115,  26,  75,   5,   8,  24,
         6,  33,   3,   6,  15,  10,   3, 141,  69,  10,   8,   4,  20,
        24,   3,  46,  10,   5,  20,   9,  13,   3,  86, 109,  26,   4,
        93, 164,  26, 162,  27,  13, 110,   5,  31,   3,   4, 165,   5,
         6,   8,  17,   5, 108,  50,   3,  46,   3,  73,  51,  63,   8,
        10,   6,  13, 141,   3, 164,   3,  17, 132, 126,   5,   7,  37,
         6,   8,   3, 101,   5, 152,  18,   7, 196,   3,  15,  87,  12,
        74,   3, 117, 118,  13,  19,   4,  54,   3,   4,  11,   3,   6,
       111,  13,   3,   7,   4,  10,   7,   7,   3,   6, 101,   5,  34,
         5,  64,  27,   4,  64,  32, 158,  26, 162,  68,  18,  2

In [23]:
edu[wines.argmax()]

'PhD'

In [24]:
edu[wines.argmin()]

'Basic'

In [25]:
sta[wines.argmax()]

'Married'

In [26]:
sta[wines.argmin()]

'Single'

In [27]:
year[wines.argmax()]

1950

In [28]:
year[wines.argmin()]

1992